// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonAnimatedUtils = require("./ReasonAnimatedUtils");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function getAnimatedValue(prim) {
  return ReasonAnimatedUtils.getAnimatedValue(prim);
}

function getAnimatedNode(prim) {
  return ReasonAnimatedUtils.getAnimatedNode(prim);
}

function classify(x) {
  var match = typeof x;
  switch (match) {
    case "boolean" :
        return /* Boolean */Block.__(3, [x]);
    case "function" :
        return /* Function */Block.__(5, [x]);
    case "number" :
        return /* Number */Block.__(4, [x]);
    case "object" :
        if (x !== null) {
          if (Array.isArray(x)) {
            return /* Array */Block.__(1, [x]);
          } else {
            var match$1 = ReasonAnimatedUtils.getAnimatedValue(x);
            var match$2 = ReasonAnimatedUtils.getAnimatedNode(x);
            if (match$1 !== undefined) {
              return /* AnimatedValue */Block.__(6, [match$1]);
            } else if (match$2 !== undefined) {
              return /* AnimatedNode */Block.__(7, [match$2]);
            } else {
              return /* Object */Block.__(0, [x]);
            }
          }
        } else {
          return /* Null */0;
        }
    case "string" :
        return /* String */Block.__(2, [x]);
    case "undefined" :
        return /* Undefined */1;
    default:
      throw [
            Caml_builtin_exceptions.assert_failure,
            /* tuple */[
              "AnimatedStyle.re",
              61,
              9
            ]
          ];
  }
}

function dictToStruct(idGenerator, updater, dict) {
  return $$Array.to_list(Js_dict.entries(dict).map((function (param) {
                    return /* tuple */[
                            param[0],
                            toValue(idGenerator, updater, param[1])
                          ];
                  })));
}

function toValue(idGenerator, updater, t) {
  var bridge = [];
  Caml_obj.caml_update_dummy(bridge, {
        updateValue: (function (value, toValue) {
            var value$1 = Curry._1(value, {
                  idGenerator: idGenerator,
                  bridge: bridge
                });
            var toValue$1 = Curry._1(toValue, {
                  idGenerator: idGenerator,
                  bridge: bridge
                });
            return Curry._2(updater, value$1, toValue$1);
          })
      });
  var encodingContext = {
    idGenerator: idGenerator,
    bridge: bridge
  };
  var match = classify(t);
  if (typeof match === "number") {
    if (match === /* Null */0) {
      return /* `Null_value */[
              -654604135,
              /* NULL_VALUE */0
            ];
    } else {
      return /* `Undefined_value */[
              629889314,
              /* UNDEFINED_VALUE */0
            ];
    }
  } else {
    switch (match.tag | 0) {
      case /* Object */0 :
          return /* `Style_value */[
                  -724205949,
                  dictToStruct(idGenerator, updater, match[0])
                ];
      case /* Array */1 :
          return /* `List_value */[
                  -769490512,
                  $$Array.to_list(match[0].map((function (param) {
                              return toValue(idGenerator, updater, param);
                            })))
                ];
      case /* String */2 :
          return /* `String_value */[
                  -663343517,
                  match[0]
                ];
      case /* Boolean */3 :
          return /* `Bool_value */[
                  258787964,
                  match[0]
                ];
      case /* Number */4 :
          return /* `Number_value */[
                  -785426853,
                  match[0]
                ];
      case /* Function */5 :
          throw [
                Caml_builtin_exceptions.assert_failure,
                /* tuple */[
                  "AnimatedStyle.re",
                  92,
                  19
                ]
              ];
      case /* AnimatedValue */6 :
          var value = Curry._1(match[0].getValue, encodingContext);
          return /* `Node */[
                  870528546,
                  {
                    node: /* `Value */[
                      -991563951,
                      value
                    ],
                    __nodeID: Curry._1(idGenerator, /* () */0)
                  }
                ];
      case /* AnimatedNode */7 :
          return /* `Node */[
                  870528546,
                  {
                    node: Curry._1(match[0].getNode, encodingContext),
                    __nodeID: Curry._1(idGenerator, /* () */0)
                  }
                ];
      
    }
  }
}

function concatStyle(styleDict, value) {
  if (typeof value === "number") {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "AnimatedStyle.re",
            111,
            9
          ]
        ];
  } else if (value.tag) {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "AnimatedStyle.re",
            111,
            9
          ]
        ];
  } else {
    Js_dict.entries(value[0]).forEach((function (param) {
            styleDict[param[0]] = param[1];
            return /* () */0;
          }));
    return /* () */0;
  }
}

function tToStruct(idGenerator, updater, t) {
  var match = classify(t);
  if (typeof match === "number") {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "AnimatedStyle.re",
            122,
            9
          ]
        ];
  } else {
    switch (match.tag | 0) {
      case /* Object */0 :
          return dictToStruct(idGenerator, updater, match[0]);
      case /* Array */1 :
          var styles = { };
          match[0].map(classify).forEach((function (param) {
                  return concatStyle(styles, param);
                }));
          return dictToStruct(idGenerator, updater, styles);
      default:
        throw [
              Caml_builtin_exceptions.assert_failure,
              /* tuple */[
                "AnimatedStyle.re",
                122,
                9
              ]
            ];
    }
  }
}

var ProtobufAnimated = 0;

var Style = 0;

var Value = 0;

var Struct = 0;

var $$Node = 0;

exports.ProtobufAnimated = ProtobufAnimated;
exports.Style = Style;
exports.Value = Value;
exports.Struct = Struct;
exports.$$Node = $$Node;
exports.getAnimatedValue = getAnimatedValue;
exports.getAnimatedNode = getAnimatedNode;
exports.classify = classify;
exports.dictToStruct = dictToStruct;
exports.toValue = toValue;
exports.concatStyle = concatStyle;
exports.tToStruct = tToStruct;
/* ./ReasonAnimatedUtils Not a pure module */
