/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const AnimatedTextBS = require('./AnimatedText.bs');

import {t as AnimatedStyle_t} from './AnimatedStyle.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = { readonly style?: AnimatedStyle_t; readonly idGenerator: (_1:void) => number };

export const name: string = AnimatedTextBS.name;
