// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function map(f, t) {
  if (t.tag) {
    return /* ClientSide */Block.__(1, [
              t[0],
              t[1]
            ]);
  } else {
    var callback = t[0];
    return /* Rpc */Block.__(0, [(function (args) {
                  return Curry._1(callback, Curry._1(f, args));
                })]);
  }
}

function makeRpc(callback) {
  return /* Rpc */Block.__(0, [callback]);
}

function makeClientSide(key, encoder) {
  return /* ClientSide */Block.__(1, [
            key,
            encoder
          ]);
}

exports.map = map;
exports.makeRpc = makeRpc;
exports.makeClientSide = makeClientSide;
/* No side effect */
