/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const FlatListBS = require('./FlatList.bs');

import {t as Callback_t} from './Callback.gen';

import {t as Style_t} from './Style.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = {
  readonly keys: string[]; 
  readonly style?: Style_t; 
  readonly onEndReached?: Callback_t<void>; 
  readonly onEndReachedThreshold?: number
};

export const name: string = FlatListBS.name;
