/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const ImageBS = require('./Image.bs');

import {t as Style_t} from './Style.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = { readonly style?: Style_t; readonly source: string };

export const name: string = ImageBS.name;
