/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:max-classes-per-file 
// tslint:disable-next-line:class-name
export abstract class encoded { protected opaque!: any }; /* simulate opaque types */
