// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function encode(instance, registerCallback) {
  if (instance.tag) {
    var inst = instance[0];
    var children = inst.children.map((function (param) {
            return encode(param, registerCallback);
          }));
    return Curry._4(inst.encode, inst.key, inst.props, registerCallback, children);
  } else {
    return {
            key: undefined,
            value: /* `RawText */[
              -687863147,
              instance[0]
            ]
          };
  }
}

var Struct = 0;

exports.Struct = Struct;
exports.encode = encode;
/* No side effect */
