// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function identify(analytics, anonymousId, traits) {
  analytics.identify({
        anonymousId: anonymousId,
        traits: traits
      });
  return /* () */0;
}

function track(analytics, anonymousId, $$event) {
  analytics.track({
        anonymousId: anonymousId,
        event: $$event
      });
  return /* () */0;
}

exports.identify = identify;
exports.track = track;
/* No side effect */
