// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Ocaml_protoc_plugin$Ocamlprotocplugin = require("ocaml-protoc-plugin-runtime-bs/src/ocaml_protoc_plugin/ocaml_protoc_plugin.bs.js");

var Serialize = Ocaml_protoc_plugin$Ocamlprotocplugin.Serialize;

var Deserialize = Ocaml_protoc_plugin$Ocamlprotocplugin.Deserialize;

var Spec = Ocaml_protoc_plugin$Ocamlprotocplugin.Spec;

var Runtime = Ocaml_protoc_plugin$Ocamlprotocplugin.Runtime;

var Reader = Ocaml_protoc_plugin$Ocamlprotocplugin.Reader;

var Writer = Ocaml_protoc_plugin$Ocamlprotocplugin.Writer;

var Service = Ocaml_protoc_plugin$Ocamlprotocplugin.Service;

var Result = Ocaml_protoc_plugin$Ocamlprotocplugin.Result;

var Extensions = Ocaml_protoc_plugin$Ocamlprotocplugin.Extensions;

var test = Ocaml_protoc_plugin$Ocamlprotocplugin.test;

exports.Serialize = Serialize;
exports.Deserialize = Deserialize;
exports.Spec = Spec;
exports.Runtime = Runtime;
exports.Reader = Reader;
exports.Writer = Writer;
exports.Service = Service;
exports.Result = Result;
exports.Extensions = Extensions;
exports.test = test;
/* Ocaml_protoc_plugin-Ocamlprotocplugin Not a pure module */
