// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Serialize = /* alias */0;

var Deserialize = /* alias */0;

var Spec = /* alias */0;

var Reader = /* alias */0;

var Writer = /* alias */0;

var Service = /* alias */0;

var Result = /* alias */0;

exports.Serialize = Serialize;
exports.Deserialize = Deserialize;
exports.Spec = Spec;
exports.Reader = Reader;
exports.Writer = Writer;
exports.Service = Service;
exports.Result = Result;
/* No side effect */
