/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {AnyStyleProp as $$t} from './StyleSheet';

// tslint:disable-next-line:interface-over-type-literal
export type t = $$t;
