/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const SwitchBS = require('./Switch.bs');

import {t as Style_t} from './Style.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = {
  readonly style?: Style_t; 
  readonly value: boolean; 
  readonly onValueChange: (_1:boolean) => void
};

export const name: string = SwitchBS.name;
