// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Callback = require("./Callback.bs.js");
var ProtoEncoders = require("./ProtoEncoders.bs.js");
var StructDecoders = require("./StructDecoders.bs.js");
var ComponentRegistry = require("./ComponentRegistry.bs.js");

var name = "Switch";

function encoder(key, param, bridge, param$1) {
  var props = param[0];
  return {
          key: key,
          value: /* `Switch */[
            -99762668,
            {
              style: ProtoEncoders.encodeStyleOptional(props),
              value: props.value,
              onValueChange: ProtoEncoders.encodeCallback(bridge, Callback.map((function (struct_) {
                          return StructDecoders.getValueField(StructDecoders.getBool, struct_);
                        }), props.onValueChange))
            }
          ]
        };
}

ComponentRegistry.add(name, encoder);

exports.name = name;
exports.encoder = encoder;
/*  Not a pure module */
