/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const TextInputBS = require('./TextInput.bs');

import {t as Callback_t} from './Callback.gen';

import {t as Style_t} from './Style.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = {
  readonly style?: Style_t; 
  readonly placeholderTextColor?: (null | string); 
  readonly placeholder?: string; 
  readonly value: string; 
  readonly onValueChange?: Callback_t<string>
};

export const name: string = TextInputBS.name;
