/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const TouchableOpacityBS = require('./TouchableOpacity.bs');

import {t as Callback_t} from './Callback.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = { readonly onPress?: Callback_t<void> };

export const name: string = TouchableOpacityBS.name;
