/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const TouchableOpacityBS = require('./TouchableOpacity.bs');

import {t as LocalProp_t} from './LocalProp.gen';

// tslint:disable-next-line:interface-over-type-literal
export type props = { readonly onPress?: (_1:void) => void; readonly localProps?: { readonly onPress?: LocalProp_t } };

export const name: string = TouchableOpacityBS.name;
