/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {tsunknown} from './TsTypes';

// tslint:disable-next-line:interface-over-type-literal
export type tsunknown = tsunknown;
