name: Publish packages to npm

on: 
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          submodules: true
      # Publishing works correctly with this version
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: Arduino/actions/setup-protoc@master
      - name: Publish packages
        run: |
          set -e

          extract() {
            # Field's key/value should be on their own line
            echo $(cat package.json \
              | grep "$1" \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g')
          }

          ROOT=$(pwd)

          yarn
          yarn build

          for PACKAGE_PATH in "./packages/nars" "./packages/nars-client" "./packages/nars-common"
          do
            cd "$PACKAGE_PATH"
            PACKAGE_VERSION=$(extract version)
            PACKAGE_NAME=$(extract name)
            NPM_VERSION=$(npm view "$PACKAGE_NAME" version)
            
            if [ "$NPM_VERSION" != "$PACKAGE_VERSION" ]
            then
              npm publish --access public
            fi
            cd "$ROOT"
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
