name: Publish packages to npm

on:
  push:
    branches:
      - master

jobs:
  runs-on: ubuntu-18.04
  publish:
    steps:
      - name: Publish nars
        uses: ./github/actions/publish
        with:
          path: packages/nars/package.json
      - name: Publish nars-common
        uses: ./github/actions/publish
        with:
          path: packages/nars-common/package.json
      - name: Publish nars-client
        uses: ./github/actions/publish
        with:
          path: packages/nars-client/package.json

